apiVersion: apps/v1
kind: Deployment
metadata:
  name: pponsub
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pponsub
  template:
    metadata:
      labels:
        app: pponsub
    spec:
      containers:
      - name: pponsub
        image: icishub.azurecr.io/heewon00/241206_mvp_ppon_sub_backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 1G
          requests:
            cpu: 100m
            memory: 50Mi
        # readinessProbe:
        #     httpGet:
        #       path: /mvp/actuator/health/readiness
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 300
        #     timeoutSeconds: 30
        #     periodSeconds: 15
        #     successThreshold: 1
        #     failureThreshold: 5
        # livenessProbe:
        #     httpGet:
        #       path: /mvp/actuator/health/liveness
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 300
        #     timeoutSeconds: 30
        #     periodSeconds: 15
        #     successThreshold: 1
        #     failureThreshold: 5    
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: SPRING_CONTEXT
            value: "pponsub"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      imagePullSecrets:
      - name: acr-secret
