apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: apigw
    spec:
      containers:
      - name: apigw
        image: icishub.azurecr.io/azure-edu/mvp_apigw
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 1G
          requests:
            cpu: 100m
            memory: 50Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
